project:
  type: website

website:
  title: "POO en Python by MCL"
  page-navigation: true
  reader-mode: true
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
    language: "fr"
  google-analytics: "G-QTG3TJ9SJQ"
  back-to-top-navigation: true
  favicon: "images/site icone.png"
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: index.qmd
        text: "ğŸ Acceuil"
      - href: cours.qmd
        text: "ğŸ“Cours"
      - href: about.qmd
        text: "ğŸ™‹ğŸ»â€â™€ï¸Ã€ Propos"

  page-footer:
    background: light
    left: "CC BY-NC 4.0 DEED
Attribution - Pas dâ€™Utilisation Commerciale 4.0 International
 Â© 2024 MÃ©nyssa Cherifa-Luron." 

format:
  html:
    code-tools: true
    highlight-style: oblivion
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)

    theme:
      light: 
        - lux
        - css/custom.scss 

    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true


