project:
  type: website

website:
  title: "POO en Python"
  page-navigation: true
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
    language: "fr"
  google-analytics: "G-QTG3TJ9SJQ"
  back-to-top-navigation: true
  favicon: "images/site icone.png"
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - href: acceuil.qmd
        text: "ğŸ Acceuil"
      - href: cours.qmd
        text: "ğŸ“Cours"
      - href: about.qmd
        text: "ğŸ™‹ğŸ»â€â™€ï¸Ã€ Propos"
  sidebar:
    background: "#F5F5F5"
    style: docked
    search: true
    logo: "images/python logo.png"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/menyssacherifaluron/
      - icon: github
        menu:
          - text: Code Source
            href: https://github.com/universdesdonnees/poo_en_python
          - text: Signaler Un Bug
            href: https://github.com/universdesdonnees/poo_en_python/issues
    contents:
      - href: acceuil.qmd
        text: "ğŸ Acceuil"
      - href: cours.qmd
        text: "ğŸ“Cours"
      - href: about.qmd
        text: "ğŸ™‹ğŸ»â€â™€ï¸Ã€ Propos"
  page-footer:
    background: light
    left: "CC BY-NC 4.0 DEED
Attribution - Pas dâ€™Utilisation Commerciale 4.0 International
 Â© 2024 MÃ©nyssa Cherifa-Luron." 

format:
  html:
    highlight-style: oblivion
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)
    theme:
      light: 
        - lux
        - css/custom.scss
    code-fold: false
    code-overflow: wrap
    css: 
      - css/custom_style.css
      - css/syllabus.css
    toc: true


