project:
  type: website

execute:
  debug: true

website:
  title: "POO en Python"
  page-navigation: true
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
    language: "fr"
  google-analytics: "G-QTG3TJ9SJQ"
  back-to-top-navigation: true
  favicon: "images/python logo.png"
  navbar:
    background: primary
    foreground: light
    left:
      - href: index_test.qmd
        text: "ğŸ Accueil"
      - href: cours/index.qmd
        text: "ğŸ“Cours"
      - href: about.qmd
        text: "ğŸ™‹ğŸ»â€â™€ï¸Ã€ Propos"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/menyssacherifaluron/
      - icon: github
        menu:
          - text: Code source
            href: https://github.com/universdesdonnees/poo_en_python
          - text: Signaler un bug
            href: https://github.com/universdesdonnees/poo_en_python/issues
  search: 
    location: navbar
    type: textbox
  sidebar:
    background: "#F5F5F5"
    style: docked
    alignment: "center"
    logo: "images/python logo.png"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/menyssacherifaluron/
      - icon: github
        href: https://github.com/universdesdonnees/poo_en_python
    contents:
      - section: "Modules"
        contents:
            - text: "---"
            - href: cours/module0.qmd
              text: "Introduction Ã  Python - Rappels essentiels"
            - text: "---"
            - href: cours/module1.qmd
              text: "POO 1. Contexte et notions Ã©lÃ©mentaires"
            - text: "---"
            - href: cours/module2.qmd
              text: "POO 2.ğŸ“ Module 2"
            - text: "---"
            - href: cours/module3.qmd
              text: "POO 3.ğŸ“ Module 3"
              
  page-footer:
    left: 'CrÃ©Ã© Â© 2024 par [MÃ©nyssa Cherifa-Luron](https://www.linkedin.com/in/menyssacherifaluron/), mise en page Quarto adaptÃ©e de [Jon Cardoso-Silva''s Quarto template for university courses](https://github.com/jonjoncardoso/quarto-template-for-university-courses)<br> Tout le contenu est sous licence (CC) (BY) (NC) [Licence Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)'
    right: 'Fait avec ğŸ et [Quarto](https://quarto.org/)<br> [Voir sur </> GitHub](https://github.com/universdesdonnees/poo_en_python)'
format:
  html:
    page-layout: full
    highlight-style: oblivion
    theme:
      light: 
        - lux
        - css/custom.scss
    code-fold: false
    code-overflow: wrap
    css: 
      - css/custom_style.css
    toc: true


