project:
  type: website

execute:
  debug: true

website:
  title: "POO en Python"
  page-navigation: true
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
    language: "fr"
  google-analytics: "G-QTG3TJ9SJQ"
  back-to-top-navigation: true
  favicon: "images/python logo.png"
  navbar:
    left:
      - href: index.qmd
        text: "ğŸ Acceuil"
      - href: cours/index.qmd
        text: "ğŸ“Cours"
      - href: about.qmd
        text: "ğŸ™‹ğŸ»â€â™€ï¸Ã€ Propos"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/menyssacherifaluron/
      - icon: github
        menu:
          - text: Code Source
            href: https://github.com/universdesdonnees/poo_en_python
          - text: Signaler Un Bug
            href: https://github.com/universdesdonnees/poo_en_python/issues
  search: 
    location: navbar
    type: textbox
  sidebar:
    background: "#F5F5F5"
    style: docked
    search: true
    logo: "images/python logo.png"
    contents:
      - section: "Modules"
        contents:
            - href: cours/module1.qmd
              text: "ğŸ“ Module 1"
            - href: cours/module2.qmd
              text: "ğŸ“ Module 2"
            - href: cours/module3.qmd
              text: "ğŸ“ Module 3"
  page-footer:
    background: light
    left: "CC BY-NC 4.0 DEED
Attribution - Pas dâ€™Utilisation Commerciale 4.0 International
 Â© 2024 MÃ©nyssa Cherifa-Luron." 

format:
  html:
    
    highlight-style: oblivion
    theme:
      light: 
        - lux
        - css/custom.scss
    code-fold: false
    code-overflow: wrap
    css: 
      - css/custom_style.css
    toc: true


